package master.thesis.monitoring.model.enums;

public enum DetailsType {
    OFFLOADED,
    NODE_OVERLOADED,
    NOT_SUPPORTED_TASK,
    RESPONSE,
    PASSED_DEADLINE,
    NO_NEXT_LINK,
    TASK_ACCEPTED,
    PENDING_AVOID_REQUEST,
    PENDING_AVOID_ACCEPTED_RESPONSE,
    PENDING_AVOID_REJECTED_RESPONSE,
    GOSSIPS_REQUEST,
    GOSSIPS_DISCOVERY_REQUEST,
    GOSSIPS_DISCOVERY_RESPONSE
}
